CREATE TABLE IF NOT EXISTS "GlobalFuelPrice" (
  "fuelId" INTEGER NOT NULL,
  "price" INTEGER NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GlobalFuelPrice_pkey" PRIMARY KEY ("fuelId")
);
